version: '3.4'

services:
  daphne:
    restart: always
    build: ../../.
    depends_on:
      - worker
      - redis
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=workshop.settings_prod
    command: bash -c 'daphne -b 0.0.0.0 -p 8000 workshop.asgi:channel_layer'
  
  worker:
    restart: always
    build: ../../.
    env_file:
      - .env
    volumes:
      - type: bind
        source: /srv/deploys/workshopdata/static
        target: /usr/src/app/static
    environment:
      - DJANGO_SETTINGS_MODULE=workshop.settings_prod
    command: ./wait-for-it.sh -p 5432 -h postgres -t 40 -- ./start_workshop.sh

  nginx:
    restart: always
    build: ./nginx/
    depends_on:
      - daphne
      - worker
    volumes:
      - type: bind
        source: /srv/deploys/workshopdata/static
        target: /usr/src/app/static
        read_only: true
    environment:
      - VIRTUAL_HOST=${HOST}
  
  postgres:
    restart: always
    image: postgres:9.6
    env_file:
      - ./.env
    volumes:
      - type: bind
        source: /srv/deploys/workshopdata/postgres
        target: /var/lib/postgresql/data
  
  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    depends_on:
      - nginx
    ports:
      - '${EXTERNAL_PORT}:80'
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /tmp/docker.sock
        read_only: true
  
  redis:
    image: redis:4.0.2
    restart: always
